### ISSUE TITLE
container exited

### ISSUE THREAD

**Issue by xiaoxinyi** [eywalker/nvidia-docker-compose#5]
My `docker-compose.yml` file : 

```yml
version: '2'
services:
  zl:
    image: zl/caffe-torch-gpu:12.27
    ports:
      - "8801:8888"
      - "6001:6008"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/dl-data:/root/dl-data
```
After `nvidia-docker-compose up -d` the container launched, but exited soon.

But when I lauch a container by `nvidia-docker` way, it worked well.

```sh
nvidia-docker run -itd -p 6008:6006 -p 8808:8888 -v `pwd`:/root/dl-data --name zl_test zl/caffe-torch-gpu:12.27
```

**Comment by eywalker** [comment]
Hi @xiaoxinyi, what happens if you use `docker-compose up -d` instead of `nvidia-docker-compose up -d`? If it still exits after using `docker-compose up -d`, then it is actually a problem more with `docker-compose`, and not specific to `nvidia-docker-compose`.

**Comment by eywalker** [comment]
That being said, I believe this is due to the fact that you pass in `-t` option when running via `nvidia-docker` which allocates a pseudo-terminal during execution. Docker-compose does not have the `-t` option, but instead you can place `tty: true` in your `docker-compose.yml` to allocate a pseudo-terminal for your service (issue described [here](https://github.com/docker/compose/issues/2610) and documentation found [here](https://docs.docker.com/compose/compose-file/#cpu-shares-cpuset-domainname-entrypoint-hostname-ipc-mac-address-mem-limit-memswap-limit-privileged-read-only-restart-stdin-open-tty-user-working-dir)). So for your `docker-compose.yml`, change it to:

```yml
version: '2'
services:
  zl:
    image: zl/caffe-torch-gpu:12.27
    ports:
      - "8801:8888"
      - "6001:6008"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/dl-data:/root/dl-data
    tty: true
```

and this should work. I just want to highlight that this is **not** `nvidia-docker-compose` specific issue/solution, but rather how the underlying `docker-compose` is designed.

Please let me know if this works for you.

**Comment by xiaoxinyi** [comment]
Hi, @eywalker. After adding `tty: true`, run `nvidia-docker-compose up -d`  It worked well. Thanks.

```yml
version: '2'
services:
  zl:
    image: zl/caffe-torch-gpu:12.27
    ports:
      - "8801:8888"
      - "6001:6008"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/dl-data:/root/dl-data
    tty: true
```
